### ISSUE TITLE
Impressum не виден

### ISSUE THREAD

**Issue by artjomusp** [quarteera/csd.quarteera.de#22]
Нет ссылки на импрессум. По закону импрессум должен быть leicht erkennbar, unmittelbar erreichbar und ständig verfügbar zu halten. Как правило это условие выполнено, если dieser Link gut sichtbar und von jeder Seite aus abrufbar ist. (https://www.bmjv.de/DE/Verbraucherportal/DigitalesTelekommunikation/Impressumspflicht/Impressumspflicht_node.html)

Необходимо добавить ссылку на импрессум и датеншуц как минимум на первую страницу, в идеале на все страницы.
![Screenshot_20210709-132614_Chrome](https://user-images.githubusercontent.com/67372684/125072739-3e14f880-e0bb-11eb-95fa-41fa7c14a01e.jpg)

**Comment by denisnur** [comment]
@vubo Лера, добавь, пожалуйста impesum еще на index.html, сейчас есть только на main_ru.html
