### ISSUE TITLE
Исправить копирайт

### ISSUE THREAD

**Issue by artjomusp** [quarteera/csd.quarteera.de#3]
в строке "Quarteera e.V. 2010-2020 Kontakt: info@quarteera.de Impressum Datenschutzerklärung" внизу страницы год 2010 лишний. Эта страница создана впервые в 2020 году, поэтому копирайт должен выглядеть так:

Quarteera e.V. 2020 Kontakt: info@quarteera.de Impressum Datenschutzerklärung

**Comment by taya23kot** [comment]
issue#3 changed to 2020
