### ISSUE TITLE
Сливаются буквы, особенно в русскоязычой версии 

### ISSUE THREAD

**Issue by artjomusp** [quarteera/csd.quarteera.de#4]
Буквы, особенно русская "в" и восклицательный знак сливаются, что затрудняет прочтение текста. примеры на картинке. Может быть можно как-то улучшить размер или начертание?

Браузер: Microsoft Edge 44.17763.831.0
ОС: Windows 10
Масштаб: 100%
Разрешение экрана: 1920*1080
Экран: 24"

![image](https://user-images.githubusercontent.com/67372684/85552603-71f1bd00-b623-11ea-98e8-6df845a9d354.png)

**Comment by denisnur** [comment]
Старая версия, закрываем
